### ISSUE TITLE
Android: gain audio focus when playing a video

### ISSUE THREAD

**Issue by iampato** [vikram25897/flutter_cached_video_player#19]
Seems the official plugin this fix this issue: pause and resuming native android background music i.e Stop mixing audio from 3rd party video/music players when a video is played.

https://github.com/flutter/plugins/pull/1755
could we do the same?

**Comment by Iampato** [comment]
fixed by the pr #20 ... waiting for a merge

**Comment by vikram25897** [comment]
A prerelease version based on video_player 2.1.1 is out now. Please try that.
