### ISSUE TITLE
Does not work with M3U8 - HLS

### ISSUE THREAD

**Issue by Jartz** [vikram25897/flutter_cached_video_player#2]

**Comment by vikram25897** [comment]
@Jartz Need for information. What doesn't work? The video doesn't play? doesn't cache? Any log would be helpful.

**Comment by jramos-tera** [comment]
Thanks for answering @vikram25897 , currently the video does not reproduce in the M3U8 format, the tests are carried out on iPhone X - V 13.5.1

**Comment by vikram25897** [comment]
@Jartz please share output of `flutter doctor -v`. Also can you share some log of this issue?

**Comment by Jartz** [comment]
Perform the test in debug, but the device does not send any error, it only does not reproduce use this video as an example: https://d1c0055u5tgd7l.cloudfront.net/videos/post/1593948150525.m3u8

all MP4 video plays without problem.

<img width="724" alt="Captura de Pantalla 2020-07-05 a la(s) 11 39 48 a  m" src="https://user-images.githubusercontent.com/19338050/86537603-d6c7d580-beb5-11ea-97c1-d4aeaa4214ac.png">

**Comment by vikram25897** [comment]
@EnderTan I am not the iOS guy, so can you please just take a look at it if you can?

**Comment by EnderTan** [comment]
@vikram25897 @Jartz This plugin is forked from the official video_player package except that it supports caching.
On iOS, the backing player is AVPlayer. The supported formats vary depending on the version of iOS, AVURLAsset class has audiovisualTypes that you can query for supported av formats.

[Check detail](https://developer.apple.com/documentation/avfoundation/avfiletype?language=objc)

**Comment by vikram25897** [comment]
@Jartz can you confirm for us if the same video is being played correctly or not using the official `video_player` plugin?

**Comment by Jartz** [comment]
@vikram25897 yes, currently the project is working with video player without any problem  https://pub.dev/packages/video_player

**Comment by EnderTan** [comment]
The caching is base on this framework https://github.com/ChangbaDevs/KTVHTTPCache
I check the Issues and it seen to not support for M3U8 - HLS for now

**Comment by vikram25897** [comment]
@EnderTan can we just add a simple if else statement so that if the URL is `m3u8`, then we don't use `KTVHTTPCache`?

**Comment by dragonkhoi** [comment]
Having this issue as well. Cached Video Player cannot play any .m3u8 / HLS files (which are supported by video_player and AVPlayer per their documentation).

**Comment by shmy** [comment]
same issue
