### ISSUE TITLE
App crashes on Target SDK >28

### ISSUE THREAD

**Issue by xanf-code** [vikram25897/flutter_cached_video_player#22]

**Comment by congfandi** [comment]
Hi guys i got this issue :

E/AndroidRuntime(10379): java.lang.NoSuchMethodError: No virtual method setAudioAttributes(Lcom/google/android/exoplayer2/audio/AudioAttributes;)V in class Lcom/google/android/exoplayer2/SimpleExoPlayer; or its super classes (declaration of 'com.google.android.exoplayer2.SimpleExoPlayer' appears in /data/app/~~s3irtV1y8EsU75HWxYZ7uA==/com.abersoft.ylva.app-XH4R5b9lU1fdunqLoukYAw==/base.apk!classes2.dex)

help please

**Comment by vikram25897** [comment]
Please check the new version. If there are still issues, report here.

**Comment by jenniestrongbow** [comment]
New version, same problem.

**Comment by vikram25897** [comment]
@jenniestrongbow Is that in debug or release?

**Comment by jenniestrongbow** [comment]
Debug.

**Comment by jenniestrongbow** [comment]
Can I ask you why you changed the main class from CachedVideoPlayer to VideoPlayer ? Thanks

**Comment by Shatha-Naami** [comment]
i have same isuess, any help ?

**Comment by amirmhmdi** [comment]
the same here !

**Comment by amirmhmdi** [comment]
-----    new AudioAttributes.Builder().setContentType(C.CONTENT_TYPE_MOVIE).build());

++++    new AudioAttributes.Builder().setContentType(C.CONTENT_TYPE_MOVIE).build(),  **_true_**);

**Comment by ciriousjoker** [comment]
Please reopen if this is still an issue.
