### ISSUE TITLE
Migrate to NNBD (Not-Null By Default)

### ISSUE THREAD

**Issue by JayPerfetto** [vikram25897/flutter_cached_video_player#24]
Please migrate this package to support null safety as is the new direction of the flutter ecosystem

Thanks!
Jason

**Comment by vikram25897** [comment]
I haven't given it any thought yet. I have to fix some more pressing issues on this plugin. Maybe then I can start working on this feature.

**Comment by JayPerfetto** [comment]
Lol enhancement requests should not be closed just because you don’t have time for them right now - label it as an enhancement and leave it open like everyone else
