### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by mnts** [vikram25897/flutter_cached_video_player#26]
on pub.dev it shows it supports macOS, but does it? if so when?

**Comment by MoshDev** [comment]
Im getting the following error when building it for MacOS:

```
    -> Fetching podspec for `cached_video_player` from `Flutter/ephemeral/.symlinks/plugins/cached_video_player/macos`
    [!] No podspec found for `cached_video_player` in `Flutter/ephemeral/.symlinks/plugins/cached_video_player/macos`
```

Tried to clean and update pods repo but no luck

**Comment by vikram25897** [comment]
MacOS doesn't yet have support for PlatformView. Even official video_player doesn't support MacOS.

**Comment by vikram25897** [comment]
It showing as supported on MacOS is an error from my side. I'll fix it soon.
