### ISSUE TITLE
where is location of cached file?

### ISSUE THREAD

**Issue by vishwajit76** [vikram25897/flutter_cached_video_player#3]
I need a video file for providing a download option for the user.

**Comment by vikram25897** [comment]
@vishwajit76 In android files are saved in cache directory. Equivalent to [path_provider](https://pub.dev/packages/path_provider)'s `getTemporaryDirectory`. For iOS, [this](https://github.com/ChangbaDevs/KTVHTTPCache) library is used. You can ask there.

**Comment by vishwajit76** [comment]
> @vishwajit76 In android files are saved in cache directory. Equivalent to [path_provider](https://pub.dev/packages/path_provider)'s `getTemporaryDirectory`. For iOS, [this](https://github.com/ChangbaDevs/KTVHTTPCache) library is used. You can ask there.

Video Player generates any cached file or not?

**Comment by vikram25897** [comment]
@vishwajit76  Yes it generates cache files, but they may not be in the format that you want. For example, on Android side, the files generated are of `.exo` format as they have been created by `ExoPlayer`. I would recommend using some download manager plugin to achieve what you want as most of the time cache files will not contain the whole video.
