### ISSUE TITLE
Please update to null safety version

### ISSUE THREAD

**Issue by ijas-cookee** [vikram25897/flutter_cached_video_player#36]
Can't use this package with Flutter 2.2. Version solving issues with other packages. Please upgrade

**Comment by wraptor** [comment]
+1

**Comment by seel-channel** [comment]
You can use the prerelease version

**Comment by GyuriMajercsik** [comment]
I can use this with Flutter 2.2 and above, just need a parameter when running or building the app: `--no-sound-null-safety`

**Comment by milanobrenovic** [comment]
+1......

**Comment by SalahAdDin** [comment]
Is this package actively mantained?

**Comment by vikram25897** [comment]
@SalahAdDin  not exactly. Not getting enough time to code but available for reviewing and merging PRs.

**Comment by SalahAdDin** [comment]
> @SalahAdDin not exactly. Not getting enough time to code but available for reviewing and merging PRs.

Can you release a `null-safety` version?

**Comment by vikram25897** [comment]
@SalahAdDin https://pub.dev/packages/cached_video_player/versions/2.0.0-dev.1

**Comment by SalahAdDin** [comment]
> @SalahAdDin https://pub.dev/packages/cached_video_player/versions/2.0.0-dev.1

do you have any ETA about the oficial release?

**Comment by vikram25897** [comment]
Try it, provide feedback and then I may release it. I have already got some feedback and will try to release as soon as I can.

**Comment by vikram25897** [comment]
@SalahAdDin https://github.com/vikram25897/flutter_cached_video_player/pull/42 provide feedback.

**Comment by SalahAdDin** [comment]
> @SalahAdDin #42 provide feedback.

Sorry, i'm using better player now.

**Comment by ciriousjoker** [comment]
Please reopen if this is still an issue.
