### ISSUE TITLE
Usage with chewie video player

### ISSUE THREAD

**Issue by bettdouglas** [vikram25897/flutter_cached_video_player#4]
Is there a way I can use the package with [chewie](https://pub.dev/packages/chewie)

**Comment by vikram25897** [comment]
@bettdouglas No it can't be used with `chewie`. Can you list down some features that are present in `Chewie` that you would want in this package?

**Comment by WaheedHussainHaans** [comment]
Is there a way to add these 
fullScreenByDefault: true,
 allowFullScreen: true,
autoPlay: false
through cachedvideocontroller only???
