### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by congfandi** [vikram25897/flutter_cached_video_player#48]
Can you guys pleasee migrate this library to null safety ? i have some project that implement  this library. now my client comeback again to improve the projcet but since this lib not migrated yet, i cannot continue the project. Thanks

**Comment by vikram25897** [comment]
https://pub.dev/packages/cached_video_player/versions/2.0.0-dev.1 Did you see this?

**Comment by Genialngash** [comment]
CachedVideoPlayerController in not defined in the null safe code

**Comment by ciriousjoker** [comment]
Please reopen if this is still an issue.
