### ISSUE TITLE
Video doesn't cache

### ISSUE THREAD

**Issue by Oladips** [vikram25897/flutter_cached_video_player#59]
I tried the normal video player and the cached video player and there's no difference between them at all, video still download everytime especially when autoloop is set to true.
Please I need a fix on this

**Comment by Paulabn** [comment]
Same problem here. Both iOS and Android. No caching what so ever. No difference from regular video_player.

**Comment by Oladips** [comment]
Fixed the issue using flutter cache manager plugin

**Comment by Sadmansamee** [comment]
@Oladips how did you solve it? any hint?
