### ISSUE TITLE
Is this package still maintained?

### ISSUE THREAD

**Issue by Kamomede** [vikram25897/flutter_cached_video_player#88]
Because no versions of cached_video_player match >2.0.4 <3.0.0 and cached_video_player 2.0.4 depends on video_player_platform_interface ^5.1.2, cached_video_player ^2.0.4 requires video_player_platform_interface ^5.1.2.
And because video_player >=2.6.1 depends on video_player_platform_interface ^6.1.0, cached_video_player ^2.0.4 is incompatible with video_player >=2.6.1.
So, because APP depends on both video_player ^2.7.0 and cached_video_player ^2.0.4, version solving failed.

**Comment by eul** [comment]
the same

**Comment by vikram25897** [comment]
Sorry this project is not actively maintained but cached_video_player is not supposed to be used alongside video_player.

**Comment by yongjieYuan** [comment]
The solutation is add dependency_overrides in your pubspec.yaml, example:

dependency_overrides:
  video_player_platform_interface: ^6.1.0
